# Generated by Django 3.1.1 on 2023-04-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230425_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
