# Generated by Django 3.1.1 on 2023-04-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='date_posted',
            new_name='created_at',
        ),
    ]
