# Generated by Django 3.1.1 on 2023-04-25 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20230426_0132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
